[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "driving-style-model"
version = "1.0.0"
description = "F1 Driving Style Analysis using Neural Networks"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
include = ["src*"]
