services:
  racingdna:
    build:
      context: ..
      dockerfile: site/Dockerfile
    container_name: racingdna_app
    ports:
      - "80:5050"
    volumes:
      - fastf1_cache:/fastf1_cache
      - ../data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

volumes:
  fastf1_cache:
